name: Automated Tests

on: push

jobs:
  Tests:
    name: "Automated tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get master
        run: git fetch origin main
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
          pip install -e src
        env:
          CI: true
      - name: Run Tests
        run: |
          #pytest . --cov=src/ --flake8 --black --mypy
          pytest . --cov=src/
          coverage xml -o coverage.xml
          coverage html
      - name: Push views
        env:
          CODOC_API_KEY: ${{ secrets.CODOC_API_KEY }}
        run: |
          python3 codoc_views
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
